// @generated by scripts/gen-cjk-font.py — do not edit by hand.
//
//! CJK console glyphs for the Stage-A framebuffer (DESIGN/005), newspaper literacy: Jōyō kanji ∪ GB2312 Level-1 (common simplified Chinese) ∪ Hangul jamo ∪ Hangul Syllables (precomposed, modern Korean) ∪ kana + CJK punctuation.
//! 16121 glyphs from GNU Unifont, packed as fixed 34-byte records sorted
//! ascending by codepoint (binary-searchable): a `u16` little-endian codepoint, then a
//! 16x16 1bpp bitmap (16 rows x 2 bytes, MSB = leftmost pixel, set bit = foreground).
//! Codepoints absent here render as the hardcoded tofu box. Beyond this set (full CJK,
//! traditional Han) waits for the BDF/GPU font stage.
//! Regenerate: `python3 scripts/gen-cjk-font.py`.

/// Packed glyph records, sorted ascending by codepoint. See [`RECORD`].
pub static CJK_FONT: &[u8] = include_bytes!("cjk_font.bin");

/// Bytes per record: 2 (`u16` LE codepoint) + 32 (16x16 bitmap).
pub const RECORD: usize = 34;

/// Number of glyph records in [`CJK_FONT`].
pub const GLYPH_COUNT: usize = 16121;
